lsst-uk/lasair-deploy

login.yaml

Issue 7 mysql connector python package

---

deploy.yaml
roles/filter/defaults/main.yml
roles/filter/tasks/filter.yml
roles/filter/tasks/main.yml

Adds filter tasks. Please check that local database setup is correct in roles/filter/tasks/filter.yml

Issue 10 filter

---

deploy.yaml
test.yaml

Issue 27 cassandra

---

roles/lasair_cephfs/tasks/main.yml

Create lasair directories

---

roles/webserver/defaults/main.yml
roles/webserver/tasks/main.yml

Django bootstrap

---

common/settings.py.j2
roles/webserver/tasks/main.yml
roles/webserver/tasks/settings.yml
roles/webserver/templates/settings.py.j2

Various settings related fixes

Issues 70 71 72 

---

login.yaml

Adds tasks to login instance setup to support vault token rotation. Actual rotation is initiated from the vault end.

Vault token rotation

---

deploy.yaml
roles/sherlock/defaults/main.yml
roles/sherlock/templates/service_settings.yaml.j2

add db port to sherlock service settings

---

deploy.yaml
heat_template.yaml
login.yaml
roles/parallel_ssh/meta/main.yml
roles/parallel_ssh/tasks/main.yml
settings.yaml
stack.yaml

Fixes #105.
Have gone with the simplest option for now of simply adding a new instance type - parallel_ssh - with an option "started" which, when set to false puts the instances in SHELVED_OFFLOADED state.

Issue 105 parallel

---

test.yaml

Add deployment checks to make sure that shared filesystems are mounted.

Add cephfs checks

---

common/settings.py.j2

Set SHERLOCK_SERVICE to None if there are no sherlock nodes defined.

handle no sherlock case

---

common/settings.py.j2

Add BACKUP_DATABASE_HOST and BACKUP_DATABASE_PORT to settings.py
Fixes #128

Settings for db backup

---

roles/jenkins/tasks/main.yml

Jenkins user

---

deploy.yaml
roles/sherlock/tasks/filesystem.yml
roles/sherlock/tasks/main.yml

Add filesystem tasks to sherlock role

---

.gitignore
README.md
settings.template

Fixes #141 
Move settings.yaml -> settings.template
Add some extra comments and change a couple of defaults
Add settings.yaml to .gitignore
Update the installation instructions in README

Change settings.yaml to template

---

roles/grafana/templates/cephfs.j2
roles/grafana/templates/disk.j2
roles/grafana/templates/host.j2
roles/grafana/templates/kafka.j2
roles/grafana/templates/load.j2
roles/grafana/templates/memory.j2
roles/grafana/templates/service.j2
roles/grafana/templates/system.json.j2
roles/grafana/templates/up.j2
roles/lasair_instance/handlers/main.yml
roles/lasair_instance/tasks/main.yml
roles/lasair_instance/tasks/prometheus.yaml
roles/lasair_instance/templates/prometheus-node-exporter.j2
roles/prometheus/templates/prometheus.yml

Adds lots of additional information to the system health dashboard.
Potentially more to be done here, but this is probably useful enough to be worth merging in its current state and adding more later.

Issue 132 monitoring

---

roles/mirrormaker/tasks/main.yml
roles/mirrormaker/templates/mirror-compose.yml.j2

Mirrormaker read from multiple topics

---

roles/sherlock/tasks/filesystem.yml
roles/sherlock/tasks/service.yml
roles/sherlock/vars/main.yml

Pull changes from develop into web refresh branch.

Update web refresh branch

---

roles/lasair_instance/tasks/prometheus.yaml
roles/lasair_instance/templates/prometheus-node-exporter.j2
roles/mirrormaker/tasks/mirrormaker.yml

Two minor changes to enable us to use prometheus textfile collector for latency reporting.
Also includes a minor unrelated fix for starting/stopping mirrormaker.

Issue 148 latency

---

roles/grafana/tasks/main.yml
roles/lasair_instance/tasks/mail.yaml
roles/lasair_instance/tasks/main.yml
roles/lasair_service/tasks/main.yml

Fixes #163 
Also includes a couple of minor fixes relating to package installs on the svc instance.

Issue 163 email
